nelmio_api_doc:
    documentation:
        info:
            title: Horus Heresy API
            description: You can find out more about Horus Heresy at [`https://warhammer40k.fandom.com/wiki/Horus_Heresy`](https://warhammer40k.fandom.com/wiki/Horus_Heresy)
            version: 1.0.0

    areas: # to filter documented areas
#        path_patterns:
#            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
#        host_patterns:
#            - ^api\.
